name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

  build:
    needs: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: linux-amd64
          - goos: linux
            goarch: arm64
            suffix: linux-arm64
          - goos: windows
            goarch: amd64
            suffix: windows-amd64.exe
          - goos: windows
            goarch: arm64
            suffix: windows-arm64.exe
          - goos: darwin
            goarch: amd64
            suffix: darwin-amd64
          - goos: darwin
            goarch: arm64
            suffix: darwin-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Install dependencies
        run: make deps

      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p bin
          go build -o bin/crush-md-${{ matrix.suffix }} ./cmd/crush-md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: crush-md-${{ matrix.suffix }}
          path: bin/crush-md-${{ matrix.suffix }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare release assets
        run: |
          mkdir -p bin
          find artifacts -name "crush-md-*" -type f -exec cp {} bin/ \;
          cd bin
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## Release ${{ steps.version.outputs.VERSION }}
            
            ### Downloads
            - **Linux (amd64)**: `crush-md-linux-amd64`
            - **Linux (arm64)**: `crush-md-linux-arm64`
            - **Windows (amd64)**: `crush-md-windows-amd64.exe`
            - **Windows (arm64)**: `crush-md-windows-arm64.exe`
            - **macOS (amd64)**: `crush-md-darwin-amd64`  
            - **macOS (arm64)**: `crush-md-darwin-arm64`
            
            ### Installation
            1. Download the appropriate binary for your platform
            2. Make it executable: `chmod +x crush-md-*` (Linux/macOS)
            3. Move to your PATH: `mv crush-md-* /usr/local/bin/crush-md`
            
            ### Verification
            Use the provided `checksums.txt` to verify the integrity of downloaded files:
            ```bash
            sha256sum -c checksums.txt
            ```
          files: |
            bin/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}