name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.4'

      - name: Get version from tag
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        run: make deps

      - name: Run tests
        run: make test

      - name: Build for all platforms
        run: make build-all

      - name: Create checksums
        run: |
          cd bin
          sha256sum * > checksums.txt

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ steps.version.outputs.VERSION }}
          body: |
            ## Release ${{ steps.version.outputs.VERSION }}
            
            ### Downloads
            - **Linux (amd64)**: `crush-md-linux-amd64`
            - **macOS (amd64)**: `crush-md-darwin-amd64`  
            - **macOS (arm64)**: `crush-md-darwin-arm64`
            - **Windows (amd64)**: `crush-md-windows-amd64.exe`
            
            ### Installation
            1. Download the appropriate binary for your platform
            2. Make it executable: `chmod +x crush-md-*` (Linux/macOS)
            3. Move to your PATH: `mv crush-md-* /usr/local/bin/crush-md`
            
            ### Verification
            Use the provided `checksums.txt` to verify the integrity of downloaded files:
            ```bash
            sha256sum -c checksums.txt
            ```
          files: |
            bin/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}